spring:
  application:
    name: simple

server:
  port: 2000

eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:${eureka.port:1111}/eureka/
    register-with-eureka:  true
    fetchRegistry: true
  instance:
    hostname: localhost