spring:
  application:
    name: ribbon-consumer
server:
  port: 3333

#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

compute-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:2000,localhost:2002
    ServerListRefreshInterval: 15000